<?php
// clear_database.php
require_once __DIR__ . '/config/db.php';

// This script safely clears schedule data while preserving permanent records
$tables = [
    'timetable',
    'subjects',
    'semesters',
    'sections',
    'batches',
    'rooms'
    // 'users' is EXCLUDED to preserve accounts (Society Presidents, Admin, CR, GR)
];

try {
    // Disable foreign key checks
    $pdo->exec("SET FOREIGN_KEY_CHECKS = 0");
    
    foreach ($tables as $table) {
        $pdo->exec("TRUNCATE TABLE `$table`");
        echo "Truncated table: $table\n";
    }

    // Preserve Faculty Members: Delete only teachers generated by PDF parser (is_faculty = 0)
    $pdo->exec("DELETE FROM teachers WHERE is_faculty = 0");
    echo "Removed non-faculty teachers while PRESERVING official faculty members.\n";
    
    // User accounts are intentionally preserved to avoid losing login credentials
    echo "User accounts preserved.\n";
    
    // Enable foreign key checks
    $pdo->exec("SET FOREIGN_KEY_CHECKS = 1");
    
    echo "Database cleared successfully.\n";
} catch (Exception $e) {
    echo "Error clearing database: " . $e->getMessage() . "\n";
}
